feat: Updated the instance with new job

diff --git a/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml b/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
--- a/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
+++ b/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
@@ -184,7 +184,7 @@ jobs:
         run: env > .env.container
 
       ### BG MANAGE ###
-      - name: BG Manage
+      - name: BG_MANAGE
         if: needs.process_environment_variables.outputs.BG_MANAGE == 'true'
         env:
           FULL_ENV_NAME: ${{ matrix.environment }}
@@ -194,16 +194,16 @@ jobs:
           bash -c "
             source /module/venv/bin/activate
 
-            echo "Executing BG Manage..."
+            echo 'Executing BG Manage...'
             if ! python /scripts/bg_manage/bg_manage.py; then
-              echo "BG Manage failed with exit code $?"
+              echo 'BG Manage failed with exit code $?'
               exit 1
             fi
           "
       ##########################
 
-      ### GENERATE INVENTORY ###
-      - name: Generate Inventory
+      ### ENV_INVENTORY_GENERATION ###
+      - name: ENV_INVENTORY_GENERATION
         if: needs.process_environment_variables.outputs.ENV_TEMPLATE_TEST == 'false' && (needs.process_environment_variables.outputs.ENV_SPECIFIC_PARAMETERS != '' || needs.process_environment_variables.outputs.ENV_TEMPLATE_NAME != '')
         run: |
           docker run --rm -v ${{ github.workspace }}:${{ env.CI_PROJECT_DIR }} -w ${{ env.CI_PROJECT_DIR }} --env-file .env.container --user root -e HOME=/root \
@@ -211,7 +211,7 @@ jobs:
             bash -c "
               source /module/venv/bin/activate
 
-              echo \"Executing inventory generation...\"
+              echo 'Executing inventory generation...'
               if ! python3 /build_env/scripts/build_env/env_inventory_generation.py; then
                 echo \"Inventory generation failed with exit code \$?\"
                 exit 1
@@ -228,7 +228,7 @@ jobs:
       ##########################
 
       ### CREDENTIAL ROTATION ###
-      - name: Credential Rotation
+      - name: CREDENTIAL_ROTATION
         if: needs.process_environment_variables.outputs.CRED_ROTATION_PAYLOAD != ''
         run: |
           docker run --rm -v ${{ github.workspace }}:${{ env.CI_PROJECT_DIR }} -w ${{ env.CI_PROJECT_DIR }} --env-file .env.container --user root -e HOME=/root \
@@ -236,9 +236,9 @@ jobs:
             bash -c "
               source /module/venv/bin/activate
 
-              echo \"Executing credential rotation...\"
+              echo 'Executing credential rotation...'
               if ! python3 /module/creds_rotation_scripts/creds_rotation_handler.py; then
-                echo \"Credential rotation failed with exit code \$?\"
+                echo 'Credential rotation failed with exit code \$?'
                 exit 1
               fi
             "
@@ -260,33 +260,39 @@ jobs:
             ${{ env.DOCKER_IMAGE_NAME_ENVGENE }}:${{ env.DOCKER_IMAGE_TAG_ENVGENE }} \
             bash -c "
               source /module/venv/bin/activate
-              echo "Executing APP_REG_DEF_PROCESS..."
-              python /module/scripts/utils/log_pipe_params.py
+              echo 'Executing APP_REG_DEF_PROCESS...'
+              python3 /module/scripts/utils/log_pipe_params.py
               /module/scripts/handle_certs.sh
               python3 /build_env/scripts/build_env/env_template/set_template_version.py
               python3 /build_env/scripts/build_env/appregdef_render.py
             "
       ##########################
 
-      ### BUILD ENV ###
-      - name: Build Env
+      ### ENV_BUILD ###
+      - name: ENV_BUILD
         if: needs.process_environment_variables.outputs.ENV_BUILDER == 'true'
         run: |
           docker run --rm -v ${{ github.workspace }}:${{ env.CI_PROJECT_DIR }} -w ${{ env.CI_PROJECT_DIR }} --env-file .env.container --user root -e HOME=/root \
             ${{ env.DOCKER_IMAGE_NAME_ENVGENE }}:${{ env.DOCKER_IMAGE_TAG_ENVGENE }} \
-            sh -c "cp ${CI_PROJECT_DIR}/.github/jobs/build_env_job.sh /tmp/build_env_job.sh && chmod +x /tmp/build_env_job.sh && bash /tmp/build_env_job.sh"
+            bash -c "
+              source /module/venv/bin/activate
+              echo 'Executing ENV_BUILD...'
+              python /module/scripts/utils/log_pipe_params.py
+              /module/scripts/handle_certs.sh
+              cd /build_env; python3 /build_env/scripts/build_env/main.py
+            "
 
       - name: Upload Build Env Package
         uses: actions/upload-artifact@v4
         if: needs.process_environment_variables.outputs.ENV_BUILDER == 'true'
         with:
-          name: build_env_${{ env.PACKAGE_NAME }}
+          name: env_build_${{ env.PACKAGE_NAME }}
           path: environments/${{ matrix.environment }}
           include-hidden-files: true
       ##########################
 
       ### GENERATE EFFECTIVE SET ###
-      - name: Generate Effective Set
+      - name: GENERATE_EFFECTIVE_SET
         if: needs.process_environment_variables.outputs.GENERATE_EFFECTIVE_SET == 'true'
         run: |
           docker run --rm -v ${{ github.workspace }}:${{ env.CI_PROJECT_DIR }} -w ${{ env.CI_PROJECT_DIR }} --env-file .env.container --user root -e HOME=/root \
@@ -320,7 +326,7 @@ jobs:
 
 
       ### GIT COMMIT ###
-      - name: Git Commit
+      - name: GIT_COMMIT
         run: |
           docker run --rm -v ${{ github.workspace }}:${{ env.CI_PROJECT_DIR }} -w ${{ env.CI_PROJECT_DIR }} --env-file .env.container --user root -e HOME=/root \
             ${{ env.DOCKER_IMAGE_NAME_ENVGENE }}:${{ env.DOCKER_IMAGE_TAG_ENVGENE }} \
